### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by girlajo** [dhis2/dhis2-android-trackercapture#12]
Hello, 
I'm interested to this app but I'm not a developper. I tried to build the app but the process fails  with the following errors : 
app/src/main/java/org/hisp/dhis2/android/trackercapture/MainActivity.java:206: error: incompatible types: LoadingFragment cannot be converted to Fragment
        showFragment(loadingFragment);
Similar error occurs at lines : 231, 278, 286,314, 

My working environment consists of :  Ubuntu 14.04, android-sdk_r24.1.2-linux, jdk1.8.0_45

**Comment by russnes** [comment]
Hi.
The master branch hasn't been updated for a little while, if you want to try the app you should use the implement-trackedentityinstance-registration branch

```
git checkout implement-trackedentityinstance-registration 
```

also you will need the SDK project https://github.com/dhis2/dhis2-android-sdk to be on the implement-tracked-entity-enrollment branch.

However, if you're not a developer I would suggest you maybe wait a little before we are able to upload a release.
