### ISSUE TITLE
Implement possibility for selecting "no program" in the selectProgramFragment

### ISSUE THREAD

**Issue by russnes** [dhis2/dhis2-android-trackercapture#35]
Sometimes there may be TEIs that have no active enrollment that user want to enroll. Another possibility is that the logged in user doesn't have access to all programs, and can't select the one a TEI is enrolled in.

Therefore it should be implemented the possibility to list all TEI for an org unit regardless of program.

**Comment by erlingfjelstad** [comment]
Server support soon to be implemented
