### ISSUE TITLE
JacksonParseError (probably due to poor Internet connection)

### ISSUE THREAD

**Issue by erlingfjelstad** [dhis2/dhis2-android-trackercapture#37]
07-05 12:44:10.453  24033-24033/org.hisp.dhis.android.trackercapture W/System.err﹕ org.hisp.dhis.android.sdk.utils.APIException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
07-05 12:44:10.454  24033-24033/org.hisp.dhis.android.trackercapture W/System.err﹕ at [Source: [B@41f52800; line: 1, column: 2]
07-05 12:44:10.454  24033-24033/org.hisp.dhis.android.trackercapture W/System.err﹕ at org.hisp.dhis.android.sdk.controllers.Dhis2$1.onSuccess(Dhis2.java:403)
07-05 12:44:10.454  24033-24033/org.hisp.dhis.android.trackercapture W/System.err﹕ at org.hisp.dhis.android.sdk.network.http.ApiRequest.request(ApiRequest.java:103)
07-05 12:44:10.455  24033-24033/org.hisp.dhis.android.trackercapture W/System.err﹕ at org.hisp.dhis.android.sdk.controllers.tasks.AuthUserTask$1.run(AuthUserTask.java:84)
07-05 12:44:10.455  24033-24033/org.hisp.dhis.android.trackercapture W/System.err﹕ Caused by: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
07-05 12:44:10.455  24033-24033/org.hisp.dhis.android.trackercapture W/System.err﹕ at [Source: [B@41f52800; line: 1, column: 2]
07-05 12:44:10.455  24033-24033/org.hisp.dhis.android.trackercapture W/System.err﹕ at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1487)
07-05 12:44:10.455  24033-24033/org.hisp.dhis.android.trackercapture W/System.err﹕ at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518)
07-05 12:44:10.455  24033-24033/org.hisp.dhis.android.trackercapture W/System.err﹕ at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:447)
07-05 12:44:10.456  24033-24033/org.hisp.dhis.android.trackercapture W/System.err﹕ at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2485)
07-05 12:44:10.456  24033-24033/org.hisp.dhis.android.trackercapture W/System.err﹕ at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:801)
07-05 12:44:10.456  24033-24033/org.hisp.dhis.android.trackercapture W/System.err﹕ at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:697)
07-05 12:44:10.456  24033-24033/org.hisp.dhis.android.trackercapture W/System.err﹕ at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3602)
07-05 12:44:10.457  24033-24033/org.hisp.dhis.android.trackercapture W/System.err﹕ at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3547)
07-05 12:44:10.457  24033-24033/org.hisp.dhis.android.trackercapture W/System.err﹕ at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2671)
07-05 12:44:10.457  24033-24033/org.hisp.dhis.android.trackercapture W/System.err﹕ at org.hisp.dhis.android.sdk.controllers.Dhis2$1.onSuccess(Dhis2.java:399)
07-05 12:44:10.457  24033-24033/org.hisp.dhis.android.trackercapture W/System.err﹕ ... 2 more
07-05 12:44:10.468  24033-24033/org.hisp.dhis.android.trackercapture D/OpenGLR

**Comment by sunbiz** [comment]
@erlingfjelstad How was this error resolved? I am getting the same error with the released 0.3.34 apk and dhis 2.24, 2.25, 2.26
