### ISSUE TITLE
Updated Code for the Tracker Capture App

### ISSUE THREAD

**Issue by i-sourabh** [dhis2/dhis2-android-trackercapture#57]
Hi Simerns,
Thanks for your help till now, I have followed all of the steps(remove the master from file name and import it ) according to you but still there are lots of the errors in the code , can you please provide me the updated code for Tracker capture ?

**Comment by russnes** [comment]
@andy003 the updated code is all there in this very GitHub repository and at least 3 people are running it. I'm sorry you are getting these errors, but maybe you should wait until we release to maven to work on these projects, if you are having problems setting up.

Like I said previously I am going to test setting up in Windows at some point in the future when time allows it.

**Comment by i-sourabh** [comment]
OK thanks.

On Sep 3, 2015 1:14 PM, Simen Skogly Russnes notifications@github.com wrote:
@andy003 the updated code is all there in this very GitHub repository and at least 3 people are running it. I'm sorry you are getting these errors, but maybe you should wait until we release to maven to work on these projects, if you are having problems setting up.

Like I said previously I am going to test setting up in Windows at some point in the future when time allows it.

---

**Comment by i-sourabh** [comment]
Hey @simernes  , I have tried all the steps again and now code is running fine. One last thing I want to ask , when I logged in with adm*\* and d****\*  , api fetches nothing for Org unit as there is nothing assigned to adm**. So can you please tell me any other user login in which it will display org units?

Thanks again.

**Comment by russnes** [comment]
That's great. Are you running against apps.dhis2.org/demo ?

**Comment by i-sourabh** [comment]
yes I have tried with apps.dhis2.org/demo

**Comment by russnes** [comment]
Ok, we have an Android test user on that server you can use. Try with user/passw android/Android123

**Comment by i-sourabh** [comment]
Thanks.
