### ISSUE TITLE
Add support for enrolling a TEI with the same attributes as used in a previous enrollment without having to modify any attributes

### ISSUE THREAD

**Issue by oysteinga** [dhis2/dhis2-android-trackercapture#69]
The required workflow to be able to use exactly the same attributes as a previous enrollment is now to change something in the enrollment fragment and change it back again to invoke a save. This seems unnecessarily difficult.

The problem with implementing this in any other way, is the lack of a cancel/undo action in the enrollment fragment. If a save is automatically initiated by the system when the + is pressed, the user has no way of cancelling a new enrollment once the + is pressed.

**Comment by russnes** [comment]
fixed for 2.22
