### ISSUE TITLE
Program Option Sets not displaying

### ISSUE THREAD

**Issue by iammash** [dhis2/dhis2-android-trackercapture#75]
I have installed version 2.24 of the tracker capture on a phone, but my program option sets could not display, so i tried to install on a different device a tablet but won't display either. The instance is on dhi2 v2.24. Any suggestions on how i can fix this or why this could be, or recommendation on which version of the app, that is known to display the options.

You can see from the screen shots below, nothing displays on the first one which is a yes/no question, however I get a male on a gender question without the other available options.

![screenshot_1](https://cloud.githubusercontent.com/assets/21077222/17996586/1d582d04-6b6a-11e6-9ff5-867da259f970.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/21077222/17996585/1d5755a0-6b6a-11e6-88b5-bc5bfdad032e.png)

I will appreciate any help.

**Comment by luckytommy** [comment]
@iammash Do you have any program rules attached to these option sets?

**Comment by erlingfjelstad** [comment]
@iammash Can you check that your options have unique codes

**Comment by iammash** [comment]
@luckytommy, yes there are program rules attached to them, could that's be the problem?

**Comment by luckytommy** [comment]
Yes, this is a known bug. We are currently working on the issue. I will message you here when a fix is out.

**Comment by iammash** [comment]
I will appreciate @luckytommy

**Comment by iammash** [comment]
And @erlingfjelstad I checked the options, they do not have codes.

**Comment by erlingfjelstad** [comment]
Please open if this is still a problem. Also try to have the same name of the option as the code of the option
