### ISSUE TITLE
Issue when App is syncronized with Local DHIS2 server

### ISSUE THREAD

**Issue by UGIuser** [dhis2/dhis2-android-trackercapture#77]
Hi all,

Actually where are working in a DHIS 2 2.24 implementation with HISP Colombia Consultants Marko García and Helder Castrillon.

We tried to use the Apps: DHIS 2 Tracker Capture and DHIS 2 Event Capture (On latest version as well), however an issue message is showed once we try to send information from Mobile devices (Cell Phone and tablets) to server. following, you will check the related issue messages:

_{"httpStatus":"Conflict","httpStatusCode":409,"status":"WARNING","message":"One more conflicts encountered, please check import summary.","response":{"responseType":"ImportSummaries","imported":0,"updated":0,"deleted":0,"ignored":1,"importSummaries":[{"responseType":"ImportSummary","status":"ERROR","description":"Event.trackedEntityInstance does not point to a valid tracked entity instance: UvruyIVLt5u","importCount":{"imported":0,"updated":0,"ignored":1,"deleted":0}}]}}_

{"httpStatus":"Conflict","httpStatusCode":409,"status":"ERROR","message":"TrackedEntityInstance does not exist."}

{"httpStatus":"Internal Server Error","httpStatusCode":500,"status":"ERROR"}

We checked sharing permissions for Data Elements, program, option sets, etc. And using a PC, the program runs normally and the information that is typed is saved without issue.

Would you mind checking with us this issue to get a root cause for it, please?

We need to solve this APP issue ASAP, because we will do a workflow in situs testing work on the next days, That to continue actions with DHIS2 implementation in Honduras.

Please let us know if it is possible to get a skype call to show you in detail this issue.

Best Regards,

**Comment by erlingfjelstad** [comment]
I think this one is resolved? Please open if it is not
