### ISSUE TITLE
Can't able to build the android app

### ISSUE THREAD

**Issue by gouravsachdeva** [dhis2/dhis2-android-trackercapture#78]
Hi,
i am trying to build the app on my laptop using this link (https://github.com/dhis2/dhis2-android-trackercapture/tree/2.23-legacy). In which all the steps are mentioned. but i can't able to build the app. Whenever i run the app i got the 2 errors which are shown below.

Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;

Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.android.dx.command.Main with arguments {--dex --num-threads=4 --output F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\transforms\dex\debug\folders\1000\1f\main F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_485d8ed16f1dad71ac0e6d22ba409acc5dfa7e45.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\commons-beanutils-1.8.3_bbded08ada47d4e8c6ec80ff7468f221ff22ef60.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\internal_impl-24.2.1_b9ffaa34e55d10c5489de6ac50ef40c2acf557e8.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_3126b2b760d47fe14c5e69a7a0c69017047ff782.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\jackson-core-2.6.3_571a0b9dc3da4d8f42c567c562180f8d1299c756.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\internal_impl-24.2.1_af518bcc148cbf473080eb2afb20624af7676bcf.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\stetho-okhttp-1.3.1_e29422ec8071e4b932d248425602b964a01073da.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_af981a4c43177e5aab2e47586d3a9f22fc85f9f2.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_95097fadac24f8bb23d5d113f970ba9fee68e110.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\retrofit-1.9.0_6b376ba8778cd0d4fd2c593b36583420e3b42d80.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\utils_b05fc14141c0d1f57a89c3f8cb31ab7cf9f6e8b6.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\gson-2.3.1_c468d4eafbb71ba9c1cc9b2ad9189dd314cbae22.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\internal_impl-23.3.0_1cb04e2d09fbefc3acc591a2f1491aa7e0901b40.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_0788e8be8c324a38415bca65fef8eb1c8c3b281e.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\support-annotations-24.2.1_ecc0fffe87637e1e8df81b67b6f605f15c993e27.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\jackson-annotations-2.6.3_fbe28fb0ec2b9e00443a717e5f903bd9a1376721.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\stetho-1.3.1_148dd97606ac0dd51637a91a618b10a83a974191.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\debug_a47f7339c6d5efad1b0a4dc04d767df567a6b229.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\otto-1.3.6_1c82fb9bb8a142e47e3bc7d7499222dce81c64bd.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_dda36c9dda95af83ee1e1fba8f4493d7f5e7c22e.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_d6d8336c500c1b71123796a0a79c3909a592078b.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_262fbe51f45b39f6b6c34f2441570e4b52305387.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_73f13b22107ffa54fb5cb5c05c0278af3ad4b341.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_3fe7f9a23062a5f71478721fb9e91f18aca83448.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_7f4a948a36a965960dd1dc77b69a3adab121650e.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_62c35d06b5beb21f228f6720ec1d47f0d794390b.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_32bc47fbb70880cbf0ec205470e75c6a9ea869e1.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\commons-lang3-3.3.2_3fb32ead8b4db3d37048ff54d974c3429bd54eb4.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\jsr305-2.0.1_3eff753c1f433dbf8dae91b19c89f1618f083808.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_76b3f7ee603f01dd0008130259991a30181da221.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_da37df5fdf70fac755ccf0aba022046e4b08fc38.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\commons-validator-1.4.0_a18015339b14a90ff42efd23592fcd3bc2e4b46f.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\commons-cli-1.2_e3211f55d0a297ec0c13d9000615befce740531e.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\okio-1.6.0_b18830d1c5d6901dcf8d48f61788e6b0c1a21172.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_b70f7c930b2923ffa9ff24ab5a402101ea6496a8.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_6df43bf6e8bf6f3c52b18105569b038621bbad16.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\jackson-databind-2.6.3_9512bdab0b6f2858397fa5e4054909c5d532f79b.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_f9f3d7e6d5d20b59e10a120b28b823610da53df3.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\converter-jackson-1.9.0_f4b192371724175db5dcafa33ddc1d9d4ebda1d5.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\joda-convert-1.8.1_752741c1c495a625a196ac8b4cbe5297e995b843.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\okhttp-urlconnection-2.4.0_045ea0f8fa87e63b3400704d05bf6f100ffa0436.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_b0c7416ef6d1ad51f99790d87a580a8c3a4476c3.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\DBFlow-Core-2.2.1_cda66d3583a5228ce19b47614ee8c17759525ba9.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\commons-digester-1.8_240d515e24279c8a5e64764b4a8421fe3c72a6d1.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\jep-2.24_6cddbd87cb79966bc106eb308245a48c6556341e.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_dc5180ef891e5fe8821e80f43e97ad81b205da01.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\joda-time-2.8.2_cde2803fe01bd5c57f454b5c520e5aff0829998f.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\jackson-datatype-joda-2.6.3_42a6e8aaddc829aaee3c5519698c7ef9cf9d3b2a.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_58a97727a4d9ea5370678abb905cb5e10f331ae1.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\commons-jexl-2.1.1_3cb1574df2192c18533692910d28f7bb9f20a5f9.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\okhttp-2.7.2_04dec073a550d1ac329f84f428dd2b41a53f3c38.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_e4d7b41fb50ee6ac0e6f8f5a3c45dba9f05355d0.jar}

**Comment by erlingfjelstad** [comment]
Hello,
Try to delete your .idea folder, it might be what is failing if you have recently upgraded your Android studio version. If you still have trouble, try to checkout this version of the sdk: https://github.com/dhis2/dhis2-android-sdk/commit/75b2315aec819a167e59f27f5efb6fc664c3910b .

**Comment by gouravsachdeva** [comment]
I tried both ways to resolve the issue but the same issue is occurring again and again and in second method the files you ask to change are available in  dhis2/dhis2-android-new-sdk. so i did change the files over there but according to your mentioned path which is in dhis2-android-sdk folder the given files doesn't exist. 

from the above mentioned methods the occurs errors are :
Error:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;

Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.android.dx.command.Main with arguments {--dex --num-threads=4 --output F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\transforms\dex\debug\folders\1000\1f\main F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_485d8ed16f1dad71ac0e6d22ba409acc5dfa7e45.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\commons-beanutils-1.8.3_bbded08ada47d4e8c6ec80ff7468f221ff22ef60.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\internal_impl-24.2.1_b9ffaa34e55d10c5489de6ac50ef40c2acf557e8.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_3126b2b760d47fe14c5e69a7a0c69017047ff782.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\jackson-core-2.6.3_571a0b9dc3da4d8f42c567c562180f8d1299c756.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\internal_impl-24.2.1_af518bcc148cbf473080eb2afb20624af7676bcf.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\stetho-okhttp-1.3.1_e29422ec8071e4b932d248425602b964a01073da.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_af981a4c43177e5aab2e47586d3a9f22fc85f9f2.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_95097fadac24f8bb23d5d113f970ba9fee68e110.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\retrofit-1.9.0_6b376ba8778cd0d4fd2c593b36583420e3b42d80.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\utils_b05fc14141c0d1f57a89c3f8cb31ab7cf9f6e8b6.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\gson-2.3.1_c468d4eafbb71ba9c1cc9b2ad9189dd314cbae22.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\internal_impl-23.3.0_1cb04e2d09fbefc3acc591a2f1491aa7e0901b40.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_0788e8be8c324a38415bca65fef8eb1c8c3b281e.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\support-annotations-24.2.1_ecc0fffe87637e1e8df81b67b6f605f15c993e27.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\jackson-annotations-2.6.3_fbe28fb0ec2b9e00443a717e5f903bd9a1376721.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\stetho-1.3.1_148dd97606ac0dd51637a91a618b10a83a974191.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\debug_a47f7339c6d5efad1b0a4dc04d767df567a6b229.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\otto-1.3.6_1c82fb9bb8a142e47e3bc7d7499222dce81c64bd.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_dda36c9dda95af83ee1e1fba8f4493d7f5e7c22e.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_d6d8336c500c1b71123796a0a79c3909a592078b.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_262fbe51f45b39f6b6c34f2441570e4b52305387.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_73f13b22107ffa54fb5cb5c05c0278af3ad4b341.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_3fe7f9a23062a5f71478721fb9e91f18aca83448.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_7f4a948a36a965960dd1dc77b69a3adab121650e.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_62c35d06b5beb21f228f6720ec1d47f0d794390b.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_32bc47fbb70880cbf0ec205470e75c6a9ea869e1.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\commons-lang3-3.3.2_3fb32ead8b4db3d37048ff54d974c3429bd54eb4.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\jsr305-2.0.1_3eff753c1f433dbf8dae91b19c89f1618f083808.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_76b3f7ee603f01dd0008130259991a30181da221.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_da37df5fdf70fac755ccf0aba022046e4b08fc38.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\commons-validator-1.4.0_a18015339b14a90ff42efd23592fcd3bc2e4b46f.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\commons-cli-1.2_e3211f55d0a297ec0c13d9000615befce740531e.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\okio-1.6.0_b18830d1c5d6901dcf8d48f61788e6b0c1a21172.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_b70f7c930b2923ffa9ff24ab5a402101ea6496a8.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_6df43bf6e8bf6f3c52b18105569b038621bbad16.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\jackson-databind-2.6.3_9512bdab0b6f2858397fa5e4054909c5d532f79b.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_f9f3d7e6d5d20b59e10a120b28b823610da53df3.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\converter-jackson-1.9.0_f4b192371724175db5dcafa33ddc1d9d4ebda1d5.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\joda-convert-1.8.1_752741c1c495a625a196ac8b4cbe5297e995b843.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\okhttp-urlconnection-2.4.0_045ea0f8fa87e63b3400704d05bf6f100ffa0436.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_b0c7416ef6d1ad51f99790d87a580a8c3a4476c3.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\DBFlow-Core-2.2.1_cda66d3583a5228ce19b47614ee8c17759525ba9.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\commons-digester-1.8_240d515e24279c8a5e64764b4a8421fe3c72a6d1.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\jep-2.24_6cddbd87cb79966bc106eb308245a48c6556341e.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_dc5180ef891e5fe8821e80f43e97ad81b205da01.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\joda-time-2.8.2_cde2803fe01bd5c57f454b5c520e5aff0829998f.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\jackson-datatype-joda-2.6.3_42a6e8aaddc829aaee3c5519698c7ef9cf9d3b2a.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_58a97727a4d9ea5370678abb905cb5e10f331ae1.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\commons-jexl-2.1.1_3cb1574df2192c18533692910d28f7bb9f20a5f9.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\okhttp-2.7.2_04dec073a550d1ac329f84f428dd2b41a53f3c38.jar F:\DHIS2_App\dhis2-android-trackercapture\app\build\intermediates\pre-dexed\debug\classes_e4d7b41fb50ee6ac0e6f8f5a3c45dba9f05355d0.jar}

**Comment by erlingfjelstad** [comment]
Duplicate
