### ISSUE TITLE
Need build for which Program Indicators working.

### ISSUE THREAD

**Issue by i-sourabh** [dhis2/dhis2-android-trackercapture#85]
Hi ,

Have test with the latest app from Play Store also but program indicators are not working on it, Please share the build for which indicators are working.

**Comment by ifoche** [comment]
Hi @i-sourabh. Can you please use jira (http://jira.dhis2.org) to report that issue? Please, it would be perfect if you could add all the context information that you can, and even better if you could replicate the problem in http://play.dhis2.org servers. Thank you in advance!
