### ISSUE TITLE
2.28 in the play store?

### ISSUE THREAD

**Issue by peg-leg** [dhis2/dhis2-android-trackercapture#91]
Currently the play store deployment says it supports up to 2.27.  Is there any timeline for releasing a 2.28 compatible version?

**Comment by ifoche** [comment]
thanks @erobinson-pb for realizing about this little mistake in the description, we've just changed it. In fact, the app is compatible with 2.28 servers already. You can read the 2.28 compatibility addition in the "what's new section".
